FROM prom/prometheus:v2.45.0

# 1. Copy your metrics configuration file
COPY prometheus.yml /etc/prometheus/prometheus.yml

# 2. Tell Prometheus to save the active query logs into /tmp (always writeable by 'nobody')
# while keeping the core TSDB block storage directed to your persistent volume mount.
CMD [ "--config.file=/etc/prometheus/prometheus.yml", \
    "--storage.tsdb.path=/prometheus", \
    "--storage.tsdb.wal-compression", \
    "--web.enable-lifecycle", \
    "--web.listen-address=:9090" ]

EXPOSE 9090